### ISSUE TITLE
Published NuGet package doesn't seem to be the most recent version

### ISSUE THREAD

**Issue by mdekok** [Haacked/mvc-metadata-conventions#9]
Hi,
The published NuGet package (0.1.2) on NuGet.org is dated 2013-12-04. There was a useful contribution by Michal Gorecki dated 2014-1-5 (Added extra fallback for error keys).
Is it possible to publish an updated version of the ModelMetadataExtensions NuGet package?
thanks in advance,
Michel de Kok

**Comment by Haacked** [comment]
Done! https://www.nuget.org/packages/ModelMetadataExtensions/
